// Exercise tutorials database
export const exerciseDatabase = {
  // Upper Body Lifts
  "Bench Press": {
    category: "Upper Body",
    muscles: ["Chest", "Triceps", "Shoulders"],
    equipment: "Barbell, Bench",
    difficulty: "Intermediate",
    description: "A fundamental compound exercise for building upper body pressing strength and chest development.",
    steps: [
      "Lie flat on the bench with your eyes under the bar",
      "Grip the bar slightly wider than shoulder-width",
      "Unrack the bar and position it over your chest",
      "Lower the bar to your mid-chest with control",
      "Press the bar back up to the starting position",
    ],
    tips: [
      "Keep your feet flat on the floor for stability",
      "Maintain a slight arch in your lower back",
      "Squeeze your shoulder blades together throughout",
      "Don't bounce the bar off your chest",
      "Breathe in on the way down, exhale on the press",
    ],
    commonMistakes: [
      "Flaring elbows too wide (keep at 45-75 degrees)",
      "Lifting hips off the bench",
      "Not using a full range of motion",
    ],
    image: "/exercises/bench-press.jpg",
  },
  "Bent Over Rows": {
    category: "Upper Body",
    muscles: ["Back", "Biceps", "Rear Delts"],
    equipment: "Barbell or Dumbbells",
    difficulty: "Intermediate",
    description: "A powerful compound movement for building a thick, strong back.",
    steps: [
      "Stand with feet shoulder-width apart, holding the bar",
      "Hinge at your hips until your torso is nearly parallel to the floor",
      "Let the bar hang at arm's length",
      "Pull the bar to your lower chest/upper abdomen",
      "Lower with control and repeat",
    ],
    tips: [
      "Keep your back flat throughout the movement",
      "Drive your elbows back, not just up",
      "Squeeze your shoulder blades at the top",
      "Don't use momentum to swing the weight",
      "Keep your core engaged to protect your lower back",
    ],
    commonMistakes: [
      "Rounding the lower back",
      "Standing too upright",
      "Using too much body English",
    ],
    image: "/exercises/bent-over-rows.jpg",
  },
  "Overhead Press": {
    category: "Upper Body",
    muscles: ["Shoulders", "Triceps", "Upper Chest"],
    equipment: "Barbell or Dumbbells",
    difficulty: "Intermediate",
    description: "The king of shoulder exercises for building overhead pressing strength.",
    steps: [
      "Stand with feet shoulder-width apart",
      "Hold the bar at shoulder height, hands just outside shoulders",
      "Brace your core and squeeze your glutes",
      "Press the bar straight overhead",
      "Lower with control back to shoulders",
    ],
    tips: [
      "Keep your core tight to prevent lower back arch",
      "Push your head through as the bar passes your face",
      "Lock out fully at the top",
      "Keep the bar path as vertical as possible",
      "Don't lean back excessively",
    ],
    commonMistakes: [
      "Excessive lower back arch",
      "Pressing the bar forward instead of straight up",
      "Not using full range of motion",
    ],
    image: "/exercises/overhead-press.jpg",
  },
  "Pull-ups or Lat Pulldown": {
    category: "Upper Body",
    muscles: ["Lats", "Biceps", "Rear Delts"],
    equipment: "Pull-up Bar or Cable Machine",
    difficulty: "Intermediate",
    description: "Essential vertical pulling movement for building a wide, V-shaped back.",
    steps: [
      "Grip the bar with hands slightly wider than shoulder-width",
      "Hang with arms fully extended (or start with arms extended for pulldowns)",
      "Pull yourself up (or pull the bar down) leading with your chest",
      "Pull until your chin clears the bar (or bar reaches upper chest)",
      "Lower with control to full extension",
    ],
    tips: [
      "Initiate the pull by depressing your shoulder blades",
      "Think about driving your elbows down and back",
      "Keep your chest up throughout the movement",
      "Avoid swinging or kipping",
      "Control the negative portion",
    ],
    commonMistakes: [
      "Using momentum to swing up",
      "Not achieving full range of motion",
      "Pulling with arms instead of back",
    ],
    image: "/exercises/pullups.jpg",
  },
  "Face Pulls": {
    category: "Upper Body",
    muscles: ["Rear Delts", "Rotator Cuff", "Upper Back"],
    equipment: "Cable Machine with Rope",
    difficulty: "Beginner",
    description: "An excellent exercise for shoulder health and posture correction.",
    steps: [
      "Set the cable at face height with a rope attachment",
      "Grab the rope with both hands, palms facing down",
      "Step back to create tension",
      "Pull the rope toward your face, separating your hands",
      "Squeeze your rear delts and slowly return",
    ],
    tips: [
      "Pull to the sides of your face, not your forehead",
      "Externally rotate at the end of the movement",
      "Keep your elbows high throughout",
      "Use lighter weight and focus on the squeeze",
      "Great for warming up or finishing a workout",
    ],
    commonMistakes: [
      "Using too much weight",
      "Not pulling far enough back",
      "Letting elbows drop",
    ],
    image: "/exercises/face-pulls.jpg",
  },
  "Bicep Curls": {
    category: "Upper Body",
    muscles: ["Biceps", "Forearms"],
    equipment: "Dumbbells or Barbell",
    difficulty: "Beginner",
    description: "The classic isolation exercise for building bigger biceps.",
    steps: [
      "Stand with dumbbells at your sides, palms facing forward",
      "Keep your elbows close to your body",
      "Curl the weights up by flexing your biceps",
      "Squeeze at the top of the movement",
      "Lower with control back to the start",
    ],
    tips: [
      "Don't swing the weights - use strict form",
      "Keep your upper arms stationary",
      "Focus on the mind-muscle connection",
      "Control the negative portion",
      "Vary grip width and angle for complete development",
    ],
    commonMistakes: [
      "Swinging the body for momentum",
      "Moving the elbows forward",
      "Not using full range of motion",
    ],
    image: "/exercises/bicep-curls.jpg",
  },
  "Tricep Pushdowns": {
    category: "Upper Body",
    muscles: ["Triceps"],
    equipment: "Cable Machine",
    difficulty: "Beginner",
    description: "An effective isolation exercise for tricep development.",
    steps: [
      "Stand facing the cable machine with a rope or bar attachment",
      "Grip the attachment and tuck your elbows at your sides",
      "Push down until your arms are fully extended",
      "Squeeze your triceps at the bottom",
      "Slowly return to the starting position",
    ],
    tips: [
      "Keep your elbows pinned to your sides",
      "Don't let your shoulders round forward",
      "Focus on squeezing the triceps at full extension",
      "Control the weight on the way back up",
      "Try different attachments for variety",
    ],
    commonMistakes: [
      "Flaring elbows out",
      "Leaning too far forward",
      "Using momentum instead of triceps",
    ],
    image: "/exercises/tricep-pushdowns.jpg",
  },

  // Lower Body Lifts
  "Barbell Back Squat": {
    category: "Lower Body",
    muscles: ["Quads", "Glutes", "Hamstrings", "Core"],
    equipment: "Barbell, Squat Rack",
    difficulty: "Intermediate",
    description: "The king of all exercises - builds total leg strength and mass.",
    steps: [
      "Position the bar on your upper back (high bar) or rear delts (low bar)",
      "Unrack and step back with feet shoulder-width apart",
      "Brace your core and initiate by pushing hips back",
      "Descend until thighs are parallel or below",
      "Drive through your feet to stand back up",
    ],
    tips: [
      "Keep your chest up and back tight throughout",
      "Track your knees over your toes",
      "Drive your knees out as you descend",
      "Maintain a neutral spine",
      "Breathe and brace before each rep",
    ],
    commonMistakes: [
      "Knees caving inward",
      "Rising hips faster than chest (good morning squat)",
      "Not hitting proper depth",
      "Losing core tightness",
    ],
    image: "/exercises/barbell-squat.jpg",
  },
  "Romanian Deadlift": {
    category: "Lower Body",
    muscles: ["Hamstrings", "Glutes", "Lower Back"],
    equipment: "Barbell or Dumbbells",
    difficulty: "Intermediate",
    description: "The best exercise for developing strong, flexible hamstrings.",
    steps: [
      "Stand with feet hip-width apart, holding the bar at thigh level",
      "Push your hips back while keeping a slight bend in your knees",
      "Lower the bar along your legs until you feel a hamstring stretch",
      "Keep your back flat throughout the movement",
      "Drive your hips forward to return to standing",
    ],
    tips: [
      "Think 'hips back' not 'bend forward'",
      "Keep the bar close to your body",
      "Feel the stretch in your hamstrings",
      "Don't round your lower back",
      "Squeeze your glutes at the top",
    ],
    commonMistakes: [
      "Rounding the lower back",
      "Bending knees too much (turns into a squat)",
      "Not hinging at the hips enough",
    ],
    image: "/exercises/romanian-deadlift.jpg",
  },
  "Walking Lunges": {
    category: "Lower Body",
    muscles: ["Quads", "Glutes", "Hamstrings"],
    equipment: "Bodyweight or Dumbbells",
    difficulty: "Beginner",
    description: "A functional unilateral exercise that builds leg strength and balance.",
    steps: [
      "Stand tall with feet together",
      "Take a large step forward with one leg",
      "Lower your back knee toward the ground",
      "Push through your front foot and bring the back leg forward",
      "Continue alternating legs",
    ],
    tips: [
      "Keep your torso upright",
      "Don't let your front knee go past your toes",
      "Step far enough to create a 90-degree angle at both knees",
      "Push through your heel, not your toes",
      "Keep your core engaged for balance",
    ],
    commonMistakes: [
      "Taking too short of steps",
      "Leaning forward excessively",
      "Knee collapsing inward",
    ],
    image: "/exercises/walking-lunges.jpg",
  },
  "Leg Press": {
    category: "Lower Body",
    muscles: ["Quads", "Glutes", "Hamstrings"],
    equipment: "Leg Press Machine",
    difficulty: "Beginner",
    description: "A safe way to load the legs heavily without spinal compression.",
    steps: [
      "Sit in the machine with your back flat against the pad",
      "Place feet shoulder-width apart on the platform",
      "Release the safety and lower the weight",
      "Descend until your knees are at 90 degrees",
      "Press through your feet to extend your legs",
    ],
    tips: [
      "Don't lock out your knees completely at the top",
      "Keep your lower back pressed into the pad",
      "Adjust foot placement to target different muscles",
      "Control the negative portion",
      "Use a full range of motion",
    ],
    commonMistakes: [
      "Letting lower back round off the pad",
      "Locking out knees aggressively",
      "Bouncing at the bottom",
    ],
    image: "/exercises/leg-press.jpg",
  },
  "Calf Raises": {
    category: "Lower Body",
    muscles: ["Calves"],
    equipment: "Bodyweight, Machine, or Dumbbells",
    difficulty: "Beginner",
    description: "Essential for building strong, defined calves.",
    steps: [
      "Stand on a raised surface with heels hanging off",
      "Hold onto something for balance if needed",
      "Lower your heels below the platform for a full stretch",
      "Rise up onto your toes as high as possible",
      "Squeeze at the top and lower with control",
    ],
    tips: [
      "Use a full range of motion for best results",
      "Pause at the top for a strong contraction",
      "Go slow on the negative portion",
      "Train both straight-leg and bent-knee variations",
      "Calves respond well to higher reps",
    ],
    commonMistakes: [
      "Using too short a range of motion",
      "Bouncing instead of controlled reps",
      "Not pausing at the top",
    ],
    image: "/exercises/calf-raises.jpg",
  },
  "Plank Hold": {
    category: "Core",
    muscles: ["Core", "Shoulders", "Glutes"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    description: "A foundational core exercise for building stability and endurance.",
    steps: [
      "Start in a push-up position on your forearms",
      "Keep your body in a straight line from head to heels",
      "Engage your core by pulling your belly button toward your spine",
      "Keep your glutes tight",
      "Hold the position for the prescribed time",
    ],
    tips: [
      "Don't let your hips sag or pike up",
      "Keep your neck neutral, looking at the floor",
      "Breathe steadily throughout",
      "Squeeze your quads to help maintain position",
      "Progress by adding time or variations",
    ],
    commonMistakes: [
      "Hips sagging toward the floor",
      "Hips piking up too high",
      "Holding breath",
    ],
    image: "/exercises/plank.jpg",
  },

  // Circuit Exercises
  "Kettlebell Swings": {
    category: "Full Body",
    muscles: ["Glutes", "Hamstrings", "Core", "Shoulders"],
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    description: "A powerful hip hinge movement that builds explosive power and conditioning.",
    steps: [
      "Stand with feet slightly wider than shoulder-width",
      "Hinge at hips and grip the kettlebell with both hands",
      "Hike the bell between your legs",
      "Explosively drive your hips forward to swing the bell",
      "Let the bell float to chest/eye height, then guide it back down",
    ],
    tips: [
      "This is a hip hinge, not a squat",
      "Power comes from your hips, not your arms",
      "Keep your arms relaxed",
      "Squeeze your glutes hard at the top",
      "Let the bell control the descent, then catch with your hips",
    ],
    commonMistakes: [
      "Squatting instead of hinging",
      "Using arms to lift the weight",
      "Rounding the lower back",
    ],
    image: "/exercises/kettlebell-swings.jpg",
  },
  "Push-ups": {
    category: "Upper Body",
    muscles: ["Chest", "Triceps", "Shoulders", "Core"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    description: "The classic bodyweight exercise for upper body pressing strength.",
    steps: [
      "Start in a plank position with hands slightly wider than shoulders",
      "Keep your body in a straight line",
      "Lower your chest toward the ground",
      "Go down until your chest nearly touches the floor",
      "Push back up to the starting position",
    ],
    tips: [
      "Keep your core tight throughout",
      "Don't let your hips sag or pike up",
      "Elbows should be at about 45 degrees from your body",
      "Look slightly ahead, not straight down",
      "Control the descent, don't just drop",
    ],
    commonMistakes: [
      "Hips sagging",
      "Flaring elbows out to 90 degrees",
      "Not using full range of motion",
    ],
    image: "/exercises/pushups.jpg",
  },
  "Goblet Squats": {
    category: "Lower Body",
    muscles: ["Quads", "Glutes", "Core"],
    equipment: "Dumbbell or Kettlebell",
    difficulty: "Beginner",
    description: "A beginner-friendly squat variation that teaches proper form.",
    steps: [
      "Hold a dumbbell or kettlebell at chest height",
      "Stand with feet shoulder-width apart or slightly wider",
      "Push your hips back and squat down",
      "Keep your chest up and elbows between your knees",
      "Drive through your feet to stand back up",
    ],
    tips: [
      "The weight helps counterbalance and keep you upright",
      "Push your knees out over your toes",
      "Go as deep as your mobility allows",
      "Keep the weight close to your body",
      "Great for learning squat mechanics",
    ],
    commonMistakes: [
      "Letting the weight pull you forward",
      "Knees caving inward",
      "Rising onto toes",
    ],
    image: "/exercises/goblet-squats.jpg",
  },
  "Dumbbell Rows": {
    category: "Upper Body",
    muscles: ["Back", "Biceps", "Rear Delts"],
    equipment: "Dumbbell, Bench",
    difficulty: "Beginner",
    description: "A unilateral back exercise that builds strength and corrects imbalances.",
    steps: [
      "Place one knee and hand on a bench for support",
      "Hold a dumbbell in your free hand, arm extended",
      "Pull the dumbbell to your hip, driving your elbow back",
      "Squeeze your back at the top",
      "Lower with control and repeat",
    ],
    tips: [
      "Keep your back flat, parallel to the floor",
      "Pull to your hip, not your chest",
      "Don't rotate your torso to help lift",
      "Focus on using your back, not your arm",
      "Keep your core engaged throughout",
    ],
    commonMistakes: [
      "Rotating the torso to cheat",
      "Pulling to the chest instead of hip",
      "Rounding the back",
    ],
    image: "/exercises/dumbbell-rows.jpg",
  },
  "Step-ups": {
    category: "Lower Body",
    muscles: ["Quads", "Glutes", "Hamstrings"],
    equipment: "Box or Bench",
    difficulty: "Beginner",
    description: "A functional single-leg exercise that mimics everyday movements.",
    steps: [
      "Stand facing a box or bench",
      "Place one foot fully on the box",
      "Drive through your heel to step up",
      "Bring your other foot up, then step back down",
      "Complete all reps on one side, then switch",
    ],
    tips: [
      "Don't push off your back foot - use the working leg",
      "Keep your torso upright",
      "Step with control, don't bounce",
      "Use a box height where your knee is at 90 degrees",
      "Add weight to progress",
    ],
    commonMistakes: [
      "Pushing off the back foot",
      "Leaning forward too much",
      "Using momentum instead of strength",
    ],
    image: "/exercises/step-ups.jpg",
  },
  "Dead Bug": {
    category: "Core",
    muscles: ["Core", "Hip Flexors"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    description: "An excellent core stability exercise that teaches bracing.",
    steps: [
      "Lie on your back with arms extended toward the ceiling",
      "Lift your legs with knees bent at 90 degrees",
      "Press your lower back into the floor",
      "Slowly extend one arm overhead while extending the opposite leg",
      "Return to start and repeat on the other side",
    ],
    tips: [
      "Keep your lower back pressed into the floor throughout",
      "Move slowly and with control",
      "Exhale as you extend, inhale as you return",
      "If your back arches, reduce range of motion",
      "Focus on maintaining core tension",
    ],
    commonMistakes: [
      "Letting the lower back arch off the floor",
      "Moving too fast",
      "Holding breath",
    ],
    image: "/exercises/dead-bug.jpg",
  },
  "Farmer's Carry": {
    category: "Full Body",
    muscles: ["Core", "Grip", "Traps", "Full Body"],
    equipment: "Dumbbells or Kettlebells",
    difficulty: "Beginner",
    description: "A functional exercise that builds grip strength and core stability.",
    steps: [
      "Pick up heavy weights in each hand",
      "Stand tall with shoulders back and core braced",
      "Walk forward with controlled, even steps",
      "Keep your shoulders level and don't lean",
      "Walk for the prescribed distance or time",
    ],
    tips: [
      "Pick heavy weights - this should be challenging",
      "Keep your core tight and posture tall",
      "Take short, quick steps",
      "Squeeze the handles as hard as you can",
      "Keep your shoulders pulled back",
    ],
    commonMistakes: [
      "Using weights that are too light",
      "Leaning to one side",
      "Letting shoulders round forward",
    ],
    image: "/exercises/farmers-carry.jpg",
  },

  // Running exercises (simplified tutorials)
  "Easy Run": {
    category: "Cardio",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Beginner",
    description: "A low-intensity run that builds aerobic base and aids recovery.",
    steps: [
      "Start with a 5-minute warm-up walk or very slow jog",
      "Run at a conversational pace (you should be able to talk)",
      "Focus on relaxed breathing and smooth form",
      "Maintain consistent effort, not speed",
      "Cool down with walking at the end",
    ],
    tips: [
      "If you can't talk, you're going too fast",
      "Keep your cadence high (170-180 steps per minute)",
      "Relax your shoulders and hands",
      "Land with your foot under your body",
      "Most of your running should be at this easy pace",
    ],
    commonMistakes: [
      "Running too fast (most common mistake!)",
      "Starting too fast and slowing down",
      "Tensing up shoulders and hands",
    ],
    image: "/exercises/easy-run.jpg",
  },
  "Tempo Run": {
    category: "Cardio",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Intermediate",
    description: "A sustained effort run that improves lactate threshold.",
    steps: [
      "Warm up with 10 minutes of easy jogging",
      "Increase pace to 'comfortably hard' - you can speak in short phrases",
      "Maintain this pace for the prescribed duration",
      "Focus on staying relaxed despite the effort",
      "Cool down with 10 minutes of easy jogging",
    ],
    tips: [
      "Tempo pace is about 85-90% of max effort",
      "You should be able to say a few words but not hold a conversation",
      "Start conservatively - you can always speed up",
      "Focus on maintaining even effort, not pace",
      "Stay relaxed in your upper body",
    ],
    commonMistakes: [
      "Starting too fast and fading",
      "Running at race pace instead of tempo",
      "Skipping the warm-up",
    ],
    image: "/exercises/tempo-run.jpg",
  },
  "Long Run": {
    category: "Cardio",
    muscles: ["Legs", "Cardiovascular System"],
    equipment: "Running Shoes",
    difficulty: "Intermediate",
    description: "Extended easy running to build endurance and mental toughness.",
    steps: [
      "Start with a 5-minute warm-up walk",
      "Run at an easy, conversational pace",
      "Focus on time on feet rather than speed",
      "Stay hydrated if running over 60 minutes",
      "Cool down with walking and stretching",
    ],
    tips: [
      "Start slower than you think you need to",
      "Bring water or plan routes with water stops for longer runs",
      "Consider nutrition for runs over 90 minutes",
      "Run by time/effort, not pace",
      "Build duration gradually (10% per week max)",
    ],
    commonMistakes: [
      "Starting too fast",
      "Not bringing hydration on hot days",
      "Increasing distance too quickly",
    ],
    image: "/exercises/long-run.jpg",
  },
};

// Get exercise by name (handles partial matches)
export function getExercise(name) {
  // Try exact match first
  if (exerciseDatabase[name]) {
    return exerciseDatabase[name];
  }

  // Try to find a partial match
  const lowerName = name.toLowerCase();
  for (const [key, value] of Object.entries(exerciseDatabase)) {
    if (key.toLowerCase().includes(lowerName) || lowerName.includes(key.toLowerCase())) {
      return value;
    }
  }

  return null;
}
